---
name: streetview

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11.3
  - requests
  - pillow

  # Testing dependencies
  - pytest=7.3.1
  - pytest-cov==4.0.0
  - pytest-vcr==1.0.2
  - isort==5.12.0
  - black==23.3.0
  - flake8==6.0.0
  - mypy==1.2.0
  - types-requests
  - types-Pillow
