---
name: streetview

channels:
  - conda-forge
  - defaults

dependencies:
  - pillow
  - pydantic
  - httpx

  # Testing dependencies
  - pytest
  - pytest-cov
  - pytest-vcr
  - pytest-asyncio
  - isort
  - black
  - flake8
  - mypy
  - types-Pillow
  - build
  - twine
